services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  adminer:
    image: adminer
    ports:
      - "8001:8080"
    depends_on:
      - db

volumes:
  db_data:
    driver: local